version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: flickspree_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flickspree
      MYSQL_USER: sunil
      MYSQL_PASSWORD: sunil
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql
